### ISSUE TITLE
Build drone launcher

### ISSUE THREAD

**Issue by rivques** [chsbacon/FTC-CENTERSTAGE-7080#4]

**Comment by rivques** [comment]
@jweder06 is doing this, but isn't in the org yet so i can't assign them

**Comment by Jweder06** [comment]
Slide and bearing have been drawn and the design has its initial Idea also on paper. I am waiting to cad and test the prototype design.

**Comment by rivques** [comment]
This is a spring-based design, right?

**Comment by Jweder06** [comment]
Yes initial drawing should be in the Imessage group chat

**Comment by rivques** [comment]
here it is, if someone else wants to see it ![image](https://github.com/chsbacon/FTC-CENTERSTAGE-7080/assets/38469076/2a1e571c-2179-47c8-b52d-db908b0816e6)

**Comment by rivques** [comment]
i currently think the best place to mount this would be roughly where the left side panel is now (cut side panel down a bit to make it fit). this would give us about 4 inches from side of hanging hook to outside of hubcaps. if we need to we can probably also move the hang hook to the other side of the arm, which would give us another inch or so. plenty of room for a plane with relatively thin wings

**Comment by rivques** [comment]
we have something that kinda works, jacob will redesign.

**Comment by rivques** [comment]
the biggest priorities with the redesign are:
1. getting it done on time
2. securely holding the drone even through heavy contact
3. getting 30 consistently
