### ISSUE TITLE
Add dead wheels

### ISSUE THREAD

**Issue by rivques** [chsbacon/FTC-CENTERSTAGE-7080#46]

**Comment by rivques** [comment]
https://gm0.org/en/latest/docs/common-mechanisms/dead-wheels.html

**Comment by GDamiani2927** [comment]
We should discuss the benefits of two vs. three wheel odometry pods, I believe we have the materials for three but that is not confirmed

**Comment by rivques** [comment]
The [OpenOdometry pods](https://openodometry.weebly.com/) are looking like a good choice, especially if we already have the wheels and some of the bearings.

**Comment by GDamiani2927** [comment]
Here is the [CAD Model](https://cvilleschools.onshape.com/documents/c525a7c7b81b322c1cf3137f/w/485aad9d2d017371dba44fad/e/04e16f3c3368f0bfb95be9e7) for the OpenOdometry pods, they look pretty good and we do have most of those materials, would have to check if the whole for the bearing is big enough for the openbuilds ones that we have used, we might have to get more.

**Comment by rivques** [comment]
honestly the more i look at this the more i want to roll our own, by the time we've adapted everything to work it'll basically be from scratch anyways imo

**Comment by rivques** [comment]
as for locations, i think the two parallel pods can go between the drive wheels on each side (and we should make our design thin enough that it doesn't extend past the edge of the hubcaps) and the perpendicular pod can go under the robot, between the intake and the shovel.

**Comment by rivques** [comment]
currently cadding these

**Comment by rivques** [comment]
cad complete, will assemble after break
