### ISSUE TITLE
slide linear slide motor sideways to parallelize strings

### ISSUE THREAD

**Issue by rivques** [chsbacon/FTC-CENTERSTAGE-7080#53]

**Comment by rivques** [comment]
will need to cut hole in sideplate to make room for tail of motor

**Comment by GDamiani2927** [comment]
Alternatively, just change the geometry of the spool to change where the grooves are positioned

**Comment by rivques** [comment]
this is difficult, because as it stands we're all the way up against the edge of the D shaft (CAD doesn't match reality, still uses old motor). we'd have to make the pull side of the spool overhang, which i'm not super excited about, but could still work. given that that side panel is going to change anyways (and the motor *just barely* can clear the wheel), i think that'd be easier, but it could go either way.
